---
roles:
  - name: rmb938.bootstrap
    src: https://github.com/rmb938/ansible-bootstrap-role.git
    version: main
    scm: git
  - name: rmb938.application
    src: https://github.com/rmb938/ansible-application-role.git
    version: main
    scm: git
