- name: Set Cloud Environment
  ansible.builtin.copy:
    dest: /etc/cloud-environment
    content: |
      CONSUL_ROLE=openstack-nova-compute
    mode: "0744"
    owner: root
    group: root
  register: cloud_environment

- name: Reboot # noqa: no-handler
  ansible.builtin.reboot:
    post_reboot_delay: 30
    reboot_timeout: 300
  when: cloud_environment.changed
